[package]
authors = ["Sytronik <sytronik210@gmail.com>"]
edition = "2021"
license = "MIT"
name = "pyin"
version = "0.1.0"

[lib]
name = "pyin"
path = "src/lib.rs"

[[bin]]
name = "pyin"
path = "src/main.rs"

[dependencies]
approx = "0.5.0"
clap = {version = "3.1.6", features = ["derive"]}
getset = "0.1.2"
ndarray = {version = "0.15.4", features = ["rayon", "approx-0_5"]}
# ndarray = {version = "0.15.4", features = ["rayon", "approx-0_5", "blas"]}
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.0"
num-traits = "0.2.14"
# openblas-src = {version = "0.10.4", features = ["cblas", "system"]}
rayon = "1.5.1"
realfft = "3.0.0"
rustfft = "6.0.1"
statrs = "0.15.0"

[dependencies.rodio]
git = "https://github.com/Sytronik/rodio.git"
rev = "e7353f7218803d94b473ea09e6d8355e8defc102"
